spring:
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver  
      url: jdbc:oracle:thin:localhost:1521:orcl
      username: orcl
      password: orcl
  aop:
    proxy-target-class:true
#  mybatis:
#      configLocation: classpath:mybatis/mybatis-config.xml

#      thymeleaf:
#          prefix:classpath:/templates
#       maximum-pool-size:100
#       max-idle=10
#       max-wait=10000
#       min-idle=5
#       initial-size=5
#       validation-query=SELECT 1
#       test-on-borrow=false
#       est-while-idle=true
#       time-between-eviction-runs-millis=18800


 # 下面为连接池的补充设置，应用到上面所有数据源中
#spring:
#  datasource:



